# Generated by Django 5.1.3 on 2024-11-29 15:17

from django.db import migrations, models

import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_authtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth_token',
        ),
        migrations.AddField(
            model_name='authtoken',
            name='expires_at',
            field=models.DateTimeField(
                default=users.models.get_token_expiration,
                verbose_name='Срок действия',
            ),
        ),
    ]
